@echo off
echo Starting AEGIS...
start "AEGIS" cmd /k "cd /d C:\users\franc\onedrive\desktop\HELENA\aegis_core && target\release\aegis.exe"
echo Waiting for AEGIS to initialise...
timeout /t 5 /nobreak
echo Starting HELENA...
cd /d C:\users\franc\onedrive\desktop\HELENA
python start_helena.py
