#!/usr/bin/env python3
"""
generate_whitelist.py

Scans your currently running processes and active network connections,
then outputs a ready-to-paste Rust whitelist for network.rs and process.rs.

Run this while your normal applications are open (browser, VS Code, etc.)
so everything you use day-to-day gets captured.

Usage:
    python generate_whitelist.py

Output:
    Prints two Rust code blocks — one for network.rs, one for process.rs.
    Also saves to whitelist_output.txt in the same directory.
"""

import psutil
import socket
import sys
from collections import defaultdict
from pathlib import Path

# ── Processes we always exclude from whitelists ────────────────────────────────
# These are either system processes that don't need whitelisting,
# or genuinely suspicious names we want to keep flagging.

ALWAYS_EXCLUDE = {
    # System processes that appear everywhere — not worth listing
    "system idle process", "system", "registry", "smss.exe", "csrss.exe",
    "wininit.exe", "winlogon.exe", "fontdrvhost.exe",
    # We want to keep flagging these
    "mimikatz.exe", "msfconsole.exe", "psexec.exe",
}

# ── Minimum connection count to include in network whitelist ───────────────────
# A process with 0 active connections doesn't need to be in the network whitelist
MIN_CONNECTIONS = 0


def get_processes():
    """Get all running processes with their names and exe paths."""
    processes = {}
    for proc in psutil.process_iter(['pid', 'name', 'exe']):
        try:
            name = (proc.info['name'] or '').lower().strip()
            exe  = (proc.info['exe']  or '').lower()
            if not name or name in ALWAYS_EXCLUDE:
                continue
            processes[proc.info['pid']] = {
                'name': name,
                'exe':  exe,
            }
        except (psutil.NoSuchProcess, psutil.AccessDenied):
            continue
    return processes


def get_network_connections(processes):
    """Get all active connections and map them to process names."""
    connected_processes = defaultdict(set)
    try:
        for conn in psutil.net_connections(kind='inet'):
            if conn.pid and conn.raddr:
                proc = processes.get(conn.pid)
                if proc:
                    connected_processes[proc['name']].add(conn.raddr.ip)
    except (psutil.AccessDenied, PermissionError):
        print("  Note: some connections may be hidden (run as admin for full view)")
    return connected_processes


def format_rust_set(names, label):
    """Format a set of names as a Rust HashSet initialiser."""
    sorted_names = sorted(names)
    lines = [f"fn {label}() -> HashSet<&'static str> {{"]
    lines.append("    [")
    
    # Group into rows of 3
    row = []
    for name in sorted_names:
        row.append(f'"{name}"')
        if len(row) == 3:
            lines.append("        " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("        " + ", ".join(row) + ",")
    
    lines.append("    ].into()")
    lines.append("}")
    return "\n".join(lines)


def main():
    print("Scanning running processes and network connections...")
    print("(Keep your normal applications open for best results)\n")

    processes       = get_processes()
    connected_procs = get_network_connections(processes)

    all_names = set(p['name'] for p in processes.values())

    # Network whitelist = processes with active connections
    network_names = set(connected_procs.keys())
    # Also add processes that are clearly network-related by name
    for name in all_names:
        if any(kw in name for kw in ['browser', 'chrome', 'firefox', 'edge',
                                      'vpn', 'network', 'wifi', 'update']):
            network_names.add(name)

    print(f"Found {len(all_names)} total processes")
    print(f"Found {len(network_names)} processes with network activity\n")

    # Show what we found with connections
    print("Processes with active network connections:")
    for name in sorted(network_names):
        ips = connected_procs.get(name, set())
        print(f"  {name:45s} ({len(ips)} connection{'s' if len(ips) != 1 else ''})")

    print()

    # Generate Rust code
    network_rust = format_rust_set(network_names, "known_safe_processes")
    process_rust = format_rust_set(all_names, "known_safe_processes")

    output = f"""
// ════════════════════════════════════════════════════════════════════════
// GENERATED WHITELIST — {__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')}
// Generated by generate_whitelist.py on this machine.
// Review before using — remove anything that looks suspicious.
// ════════════════════════════════════════════════════════════════════════

// ── For network.rs ────────────────────────────────────────────────────────────
// Replace the existing known_safe_processes() function with this one.
// Contains only processes observed making network connections.

{network_rust}


// ── For process.rs ────────────────────────────────────────────────────────────  
// Replace the existing known_safe_processes() function with this one.
// Contains all running processes (broader — suppresses new_process noise).

{process_rust}
"""

    print(output)

    out_path = Path("whitelist_output.txt")
    out_path.write_text(output, encoding='utf-8')
    print(f"\nAlso saved to: {out_path.resolve()}")
    print("\nReview the output carefully before pasting into your Rust files.")
    print("Remove any entries that look unfamiliar or suspicious.")


if __name__ == "__main__":
    main()
