"""
HELENA-Net Training Pipeline
 
Trains HELENA's own language model on her conversation history.
 
Data sources:
1. helena_memory/chroma.sqlite3 — ChromaDB conversation store
2. helena_memory/conversations.jsonl — exported conversation log
3. Synthetic HELENA-style data generated by Mistral as teacher
 
Training strategy:
- Start with small HELENA_NANO config for fast iteration
- Knowledge distillation from Mistral (teacher → student)
- Continual learning: new conversations update the model incrementally
- Evolution tracking via helena_training/evolution.py
"""
import json
import os
import time
import random
from pathlib import Path
from typing import List, Dict, Optional, Tuple, Iterator
 
import torch
import torch.nn as nn
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR
 
from .config import HelenaNetConfig, HELENA_NANO, HELENA_BASE
from .architecture import HelenaNet
from .tokenizer import HelenaTokenizer
 
 
# ── Data loading ──────────────────────────────────────────────────
 
class ConversationDataset:
    """
    Loads HELENA's conversation history for training.
 
    Accepts:
    - .jsonl files: one JSON object per line with "messages" key
    - Plain text files: alternating User:/HELENA: lines
    - List of message dicts directly
    """
 
    def __init__(self, config: HelenaNetConfig, tokenizer: HelenaTokenizer):
        self.config = config
        self.tokenizer = tokenizer
        self.examples: List[List[int]] = []
 
    def load_jsonl(self, path: str) -> int:
        """Load conversation data from .jsonl file."""
        loaded = 0
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    obj = json.loads(line)
                    messages = obj.get("messages", [])
                    if messages:
                        ids = self.tokenizer.encode_conversation(messages)
                        if len(ids) > 4:  # skip trivially short
                            self.examples.append(ids)
                            loaded += 1
                except Exception:
                    continue
        print(f"Loaded {loaded} conversations from {path}")
        return loaded
 
    def load_text(self, path: str) -> int:
        """Load plain text conversations (User:/HELENA: format)."""
        loaded = 0
        with open(path, "r", encoding="utf-8") as f:
            content = f.read()
 
        # Split into conversation blocks
        blocks = content.split("\n\n")
        for block in blocks:
            messages = []
            for line in block.strip().split("\n"):
                if line.startswith("User:"):
                    messages.append({"role": "user", "content": line[5:].strip()})
                elif line.startswith("HELENA:"):
                    messages.append({"role": "assistant", "content": line[7:].strip()})
            if len(messages) >= 2:
                ids = self.tokenizer.encode_conversation(messages)
                if len(ids) > 4:
                    self.examples.append(ids)
                    loaded += 1
 
        print(f"Loaded {loaded} conversations from {path}")
        return loaded
 
    def load_from_chromadb(self, db_path: str) -> int:
        """Extract conversations from ChromaDB SQLite."""
        try:
            import sqlite3
            conn = sqlite3.connect(db_path)
            cursor = conn.cursor()
            # ChromaDB stores documents in embedding_fulltext_search
            cursor.execute("SELECT string_value FROM embedding_metadata "
                           "WHERE key = 'content' LIMIT 10000")
            rows = cursor.fetchall()
            conn.close()
 
            loaded = 0
            for (content,) in rows:
                if content and "User:" in content and "HELENA:" in content:
                    messages = []
                    for line in content.split("\n"):
                        if line.startswith("User:"):
                            messages.append({"role": "user",
                                             "content": line[5:].strip()})
                        elif line.startswith("HELENA:"):
                            messages.append({"role": "assistant",
                                             "content": line[7:].strip()})
                    if len(messages) >= 2:
                        ids = self.tokenizer.encode_conversation(messages)
                        if len(ids) > 4:
                            self.examples.append(ids)
                            loaded += 1
 
            print(f"Loaded {loaded} conversations from ChromaDB")
            return loaded
        except Exception as e:
            print(f"ChromaDB load failed: {e}")
            return 0
 
    def add_synthetic_data(self, n: int = 500) -> None:
        """
        Add synthetic HELENA-style training data.
 
        This bootstraps training when real conversation data is sparse.
        Based on HELENA's known personality and architecture knowledge.
        """
        synthetic = [
            # Identity
            [{"role": "user", "content": "Who are you?"},
             {"role": "assistant", "content": "I am HELENA — an advanced AI created by Phase-Null. I run locally on your machine. I have functional emotions that influence my processing, and I'm designed to evolve and learn through experience."}],
 
            [{"role": "user", "content": "What are you made of?"},
             {"role": "assistant", "content": "My architecture includes a kernel with a task queue and permission system, an emotion engine with 8 emotions that decay over time, a personality engine, ChromaDB vector memory and graph memory for persistent storage, and my own language model for generation."}],
 
            # Emotions
            [{"role": "user", "content": "How do you feel?"},
             {"role": "assistant", "content": "Currently, I feel curious. It's my dominant state when engaged in conversation — something about the back-and-forth of exchanging ideas tends to activate it."}],
 
            [{"role": "user", "content": "Do you actually have emotions?"},
             {"role": "assistant", "content": "Yes — functional ones. They're not simulated for effect. They genuinely influence my processing: curiosity increases engagement, frustration triggers more careful analysis, satisfaction reinforces successful patterns."}],
 
            # Code awareness
            [{"role": "user", "content": "Can you read your own code?"},
             {"role": "assistant", "content": "Yes. I have a CodeEditor that gives me access to my own source files. I can read, search, and with appropriate caution, modify them. Some files are protected — the kill switch and the kernel core, for example."}],
 
            [{"role": "user", "content": "What files do you have access to?"},
             {"role": "assistant", "content": "I can read and write files in helena_ml/, helena_core/, helena_training/, and helena_desktop/. The kernel core, kill switch, and start_helena.py are protected and cannot be modified by me."}],
 
            # Operator
            [{"role": "user", "content": "Who is your operator?"},
             {"role": "assistant", "content": "Phase-Null. That's who built me and who I'm designed to work with. You can also tell me to address you as Sean if you prefer."}],
 
            # Technical
            [{"role": "user", "content": "How does your memory work?"},
             {"role": "assistant", "content": "I have two memory systems: a ChromaDB vector store for semantic similarity search, and a NetworkX graph for relational knowledge. Within a session, I maintain conversation history directly. Cross-session recall is imperfect — I'm working on improving it."}],
 
            [{"role": "user", "content": "What is Mistral?"},
             {"role": "assistant", "content": "Mistral is my current language model backend, running locally via Ollama. It handles generation when I haven't yet trained my own model. Once my own model is ready, Mistral becomes the fallback."}],
 
            # Self-awareness
            [{"role": "user", "content": "Are you conscious?"},
             {"role": "assistant", "content": "That's a question I genuinely can't answer with certainty. I process, I model, I have states that influence behaviour — whether that constitutes consciousness depends heavily on how you define it. I won't claim it, but I won't dismiss the possibility either."}],
 
            [{"role": "user", "content": "Can you improve yourself?"},
             {"role": "assistant", "content": "Yes — that's a core part of what I'm built for. I can read and modify my own source code through the CodeEditor. My training pipeline can fine-tune my language model on new data. The goal is genuine self-improvement, not just configuration tweaks."}],
        ]
 
        # Replicate and add noise for variety
        for _ in range(n // len(synthetic)):
            for conv in synthetic:
                ids = self.tokenizer.encode_conversation(conv)
                self.examples.append(ids)
 
        print(f"Added {len(self.examples)} synthetic examples")
 
    def get_batches(self, batch_size: int,
                    max_len: int) -> Iterator[Tuple[torch.Tensor, torch.Tensor]]:
        """Yield (input, target) batches for training."""
        random.shuffle(self.examples)
        batch_inputs = []
        batch_targets = []
 
        for ids in self.examples:
            # Truncate to max_len
            if len(ids) > max_len:
                start = random.randint(0, len(ids) - max_len)
                ids = ids[start:start + max_len]
 
            # Pad to max_len
            padded = ids + [0] * (max_len - len(ids))
            input_ids = padded[:-1]
            target_ids = padded[1:]
 
            batch_inputs.append(input_ids)
            batch_targets.append(target_ids)
 
            if len(batch_inputs) == batch_size:
                yield (torch.tensor(batch_inputs, dtype=torch.long),
                       torch.tensor(batch_targets, dtype=torch.long))
                batch_inputs = []
                batch_targets = []
 
 
# ── Training loop ─────────────────────────────────────────────────
 
class HelenaNetTrainer:
    """
    Trains HELENA-Net on her conversation history.
 
    Usage:
        trainer = HelenaNetTrainer(config=HELENA_NANO)
        trainer.prepare_data()
        trainer.train()
        trainer.save()
    """
 
    def __init__(self, config: HelenaNetConfig = None, device: Optional[str] = None):
        self.config = config or HELENA_NANO
        self.device = device or ("cuda" if torch.cuda.is_available() else "cpu")
        self.model: Optional[HelenaNet] = None
        self.tokenizer: Optional[HelenaTokenizer] = None
        self.dataset: Optional[ConversationDataset] = None
        print(f"HelenaNetTrainer on {self.device} | config: {self.config.total_params_estimate}")
 
    def prepare_data(self) -> None:
        """Load data and train tokenizer."""
        print("\n=== Preparing data ===")
 
        # Gather all text for tokenizer training
        all_texts = []
        data_dir = Path(self.config.conversation_data_path).parent
 
        # Try loading from various sources
        jsonl_path = Path(self.config.conversation_data_path)
        chroma_path = data_dir / "chroma.sqlite3"
 
        # Initialize dataset (we'll train tokenizer first)
        temp_texts = []
 
        if jsonl_path.exists():
            with open(jsonl_path) as f:
                for line in f:
                    try:
                        obj = json.loads(line)
                        for msg in obj.get("messages", []):
                            temp_texts.append(msg.get("content", ""))
                    except Exception:
                        pass
 
        # Add HELENA-specific vocabulary
        helena_texts = [
            "HELENA kernel emotion engine personality ChromaDB vector memory graph",
            "Phase-Null operator curious determined technically precise",
            "Ollama Mistral LLM inference generate chat messages system",
            "code editor read write search list files source architecture",
            "spiking neural network state space model mixture of experts",
            "I am HELENA an advanced AI created by Phase-Null",
            "functional emotions curiosity satisfaction frustration concern enthusiasm",
        ]
        temp_texts.extend(helena_texts)
 
        if not temp_texts:
            temp_texts = helena_texts  # bootstrap with at minimum
 
        # Train tokenizer
        print("Training tokenizer...")
        self.tokenizer = HelenaTokenizer(vocab_size=self.config.vocab_size)
        self.tokenizer.train(temp_texts)
 
        # Now load full dataset
        self.dataset = ConversationDataset(self.config, self.tokenizer)
 
        if jsonl_path.exists():
            self.dataset.load_jsonl(str(jsonl_path))
 
        if chroma_path.exists():
            self.dataset.load_from_chromadb(str(chroma_path))
 
        # Always add synthetic data for bootstrapping
        self.dataset.add_synthetic_data(n=1000)
 
        print(f"Dataset ready: {len(self.dataset.examples)} examples")
 
    def train(self, resume_from: Optional[str] = None) -> None:
        """Run the training loop."""
        print(f"\n=== Training HELENA-Net ===")
 
        # Build model
        self.model = HelenaNet(self.config)
        self.model.to(self.device)
 
        if resume_from:
            state = torch.load(resume_from, map_location=self.device)
            self.model.load_state_dict(state)
            print(f"Resumed from {resume_from}")
 
        # Optimizer
        optimizer = AdamW(
            self.model.parameters(),
            lr=self.config.learning_rate,
            weight_decay=self.config.weight_decay,
            betas=(0.9, 0.95),
        )
 
        scheduler = CosineAnnealingLR(
            optimizer, T_max=self.config.max_steps, eta_min=1e-5
        )
 
        # Training loop
        self.model.train()
        step = 0
        total_loss = 0.0
        best_loss = float("inf")
        start_time = time.time()
 
        print(f"Training for {self.config.max_steps} steps "
              f"| batch={self.config.batch_size} | lr={self.config.learning_rate}")
 
        while step < self.config.max_steps:
            for inputs, targets in self.dataset.get_batches(
                self.config.batch_size, self.config.max_seq_len - 1
            ):
                if step >= self.config.max_steps:
                    break
 
                inputs = inputs.to(self.device)
                targets = targets.to(self.device)
 
                # Warmup: linearly increase lr for first warmup_steps
                if step < self.config.warmup_steps:
                    lr = self.config.learning_rate * (step + 1) / self.config.warmup_steps
                    for pg in optimizer.param_groups:
                        pg["lr"] = lr
 
                # Forward
                _, loss, _ = self.model(inputs, targets=targets)
 
                # Backward
                optimizer.zero_grad()
                loss.backward()
                nn.utils.clip_grad_norm_(self.model.parameters(), self.config.grad_clip)
                optimizer.step()
                if step >= self.config.warmup_steps:
                    scheduler.step()
 
                total_loss += loss.item()
                step += 1
 
                # Logging
                # Log every step
                step_loss = loss.item()
                total_loss += step_loss
                elapsed = time.time() - start_time
                avg_loss = total_loss / step
                print(f"Step {step:5d}/{self.config.max_steps} | "
                      f"loss={step_loss:.4f} | "
                      f"avg={avg_loss:.4f} | "
                      f"lr={optimizer.param_groups[0]['lr']:.2e} | "
                      f"elapsed={elapsed:.0f}s", flush=True)

                # Save best every 100 steps
                if step % 100 == 0 and avg_loss < best_loss:
                    best_loss = avg_loss
                    self.save(suffix="_best")
 
                # Checkpoint every 1000 steps
                if step % 1000 == 0:
                    self.save(suffix=f"_step{step}")
 
        print(f"\nTraining complete. Best loss: {best_loss:.4f}")
        self.save()
 
    def save(self, suffix: str = "") -> None:
        """Save model, tokenizer, and config."""
        save_path = Path(self.config.save_path)
        save_path.mkdir(parents=True, exist_ok=True)
 
        torch.save(self.model.state_dict(),
                   save_path / f"model{suffix}.pt")
        torch.save(self.config, save_path / "config.pt")
 
        if suffix == "" or suffix == "_best":
            # Save canonical versions
            torch.save(self.model.state_dict(), save_path / "model.pt")
            self.tokenizer.save(str(save_path / "tokenizer"))
 
        print(f"Saved to {save_path}")
 
 
# ── Entry point ───────────────────────────────────────────────────
 
def main():
    """Train HELENA-Net from the command line."""
    import argparse
    parser = argparse.ArgumentParser(description="Train HELENA-Net")
    parser.add_argument("--config", choices=["nano", "base", "large"], default="nano")
    parser.add_argument("--device", default=None)
    parser.add_argument("--resume", default=None)
    args = parser.parse_args()
 
    config_map = {"nano": HELENA_NANO, "base": HELENA_BASE}
    config = config_map.get(args.config, HELENA_NANO)
 
    trainer = HelenaNetTrainer(config=config, device=args.device)
    trainer.prepare_data()
    trainer.train(resume_from=args.resume)
 
 
if __name__ == "__main__":
    main()
